
#person:
#  lastname: Tony
#  age: 20
#  boss: false
#  birth: 2017/12/12
#
##  行内写法
#  maps: {k1: v1,k2: v2}
#  lists:
#    - lisi
#    - zhangsan
#
#  dog:
#    name: lucy
#    age: 2
# 代码块一
server:
  port: 8081
#spring:
#  profiles:
#    active: dev #选定开发环境
#---
## 代码块二
#server:
#  port: 8081
#spring:
#  profiles: dev
#
#---
## 代码块三
#server:
#  port: 8082
#spring:
#  profiles: pro #指定开发环境
